# Generated by Django 6.0.6 on 2026-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponsetype', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('resposetext', models.CharField(max_length=2000)),
                ('posteddate', models.CharField(verbose_name=30)),
            ],
        ),
    ]
