# Generated by Django 6.0.6 on 2026-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='posteddate',
            field=models.CharField(max_length=30),
        ),
    ]
