# Generated by Django 6.0.6 on 2026-10-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_response_posteddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='resposetext',
            new_name='responsetext',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='reponsetype',
            new_name='responsetype',
        ),
    ]
